import type { Metadata } from "next";
import { getLegalPageNavigation, LegalPage } from "@/components/legal/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy | InsureFlow" };

export default async function PrivacyPage() {
  const navigation = await getLegalPageNavigation();
  return <LegalPage {...navigation} title="Privacy Policy" introduction="This notice describes the information handled by the InsureFlow demonstration and how it supports the product experience." sections={[
    { title: "Information collected", paragraphs: ["The demonstration may process information you provide, records created through use of the application, and limited technical information required to operate and secure the service."] },
    { title: "Account information", paragraphs: ["Account data may include your name, email address, phone number, login-related identifiers, and assigned portal role."] },
    { title: "Vehicle and policy information", paragraphs: ["Vehicle details, policy records, coverage selections, simulated quotes, and policy-link verification information may be stored to demonstrate customer workflows."] },
    { title: "Claim information and uploaded documents", paragraphs: ["Claim descriptions, accident details, contact information, photographs, police reports, and repair estimates may be processed when submitted to the demonstration."] },
    { title: "How information is used", bullets: ["Provide account, policy, claim, and administrative demonstration features.", "Authenticate users and apply role-based access.", "Send transactional confirmation and verification messages.", "Provide advisory AI coverage guidance and generate claim-analysis outputs for human review.", "Maintain the security and reliability of the demonstration."] },
    { title: "Authentication and security", paragraphs: ["InsureFlow uses access controls, authenticated sessions, server-side authorization, and role-based access. Uploaded claim and policy documents use private access controls and authorized access mechanisms, including short-lived signed document links. No system can guarantee absolute security."] },
    { title: "Cookies and browser storage", paragraphs: ["InsureFlow uses essential cookies and browser storage for authentication, session continuity, security, and remembering acknowledgement of the public cookie notice. It does not currently use advertising, analytics, marketing, or behavioral-tracking cookies. Essential storage is not blocked by the cookie notice. See the Cookie Policy for more information."] },
    { title: "AI processing", paragraphs: ["Claim information and supported evidence may be sent through OpenRouter to an available AI model provider for analysis. Depending on the model selected through OpenRouter, information may be processed by a downstream model provider. AI coverage guidance may similarly use vehicle information, coverage preferences, and optional context you provide.", "InsureFlow intentionally sends only information needed for the AI task where practical and minimizes the account identity and internal metadata sent with AI requests. However, documents and images submitted for claim analysis may themselves contain personal or sensitive information and are not guaranteed to be anonymized before processing.", "AI may summarize information or identify missing details, inconsistencies, and review flags. AI-assisted outputs require human review. AI does not approve or reject claims or make binding claim, coverage, pricing, or underwriting decisions."] },
    { title: "Email communications", paragraphs: ["Claim and policy notifications, policy documents, policy-link verification codes, and password-change verification messages may be delivered through Resend. Authentication emails, including account and email confirmations and password reset links, are sent through the configured authentication email service."] },
    { title: "Data retention", paragraphs: ["Demonstration data may remain in the configured database and storage services until it is removed during project maintenance. Operational and verification records may be retained for as long as reasonably needed to support the demonstration, security, and maintenance. InsureFlow does not currently publish a fixed retention schedule for all data categories."] },
    { title: "Verification and operational records", paragraphs: ["InsureFlow may create temporary or operational records needed to support features such as email verification, policy linking, password verification and recovery, duplicate-submission protection, and system security. These records are used to operate the demonstration and are not intended as customer-facing insurance records."] },
    { title: "Third-party services", paragraphs: ["The current architecture uses Supabase for authentication, database, and file storage; Resend for transactional and verification email; and OpenRouter and downstream model providers for AI-assisted coverage guidance and claim analysis. Their handling of data is also governed by their own terms and policies."] },
    { title: "User choices", paragraphs: ["You may choose not to enter optional information or upload optional documents. Some demonstration features require particular information to operate."] },
    { title: "Data access and deletion", paragraphs: ["The current portfolio version does not provide a complete self-service data export or deletion workflow. Demonstration data may be removed as part of project maintenance."] },
    { title: "Demo environment", paragraphs: ["Because InsureFlow is a portfolio demonstration, use demonstration or non-sensitive data wherever possible. Avoid submitting real sensitive personal, financial, medical, legal, or insurance information."] },
    { title: "Contact", paragraphs: ["For demonstration-related privacy questions, use the contact channel provided with the InsureFlow project portfolio."] },
    { title: "Last updated", paragraphs: ["October 1, 2026"] },
  ]} />;
}
